name: CI

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - users: actions/checkout@v2

      - name: Setup do NodeJS
        uses: actions/setup-node@v3.0.0
        with: 
          node-version: 22.14.0
